# Generated by Django 5.2.3 on 2025-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mujer',
            name='areas_investigacion',
        ),
        migrations.AddField(
            model_name='mujer',
            name='areas_investigacion',
            field=models.ManyToManyField(blank=True, related_name='mujeres', to='mujeres.areainvestigacion'),
        ),
    ]
