# Generated by Django 5.2.1 on 2025-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
