# Generated by Django 5.2.3 on 2025-06-19 00:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0002_remove_mujer_areas_investigacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mujer',
            name='areas_investigacion',
        ),
        migrations.AddField(
            model_name='mujer',
            name='areas_investigacion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Áreas de investigación'),
        ),
    ]
