# Generated by Django 5.2.2 on 2025-06-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0002_visitedlugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='ar_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL de Realidad Aumentada'),
        ),
    ]
