# Generated by Django 5.2.1 on 2025-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0002_lugar_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mujer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
