# Generated by Django 5.2.2 on 2025-06-18 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0003_lugar_ar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLugarRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mujeres.lugar')),
                ('mujer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_visitadas', to='mujeres.mujer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_lugares_ruta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'mujer', 'lugar')},
            },
        ),
    ]
