# Generated by Django 5.2.1 on 2025-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0003_alter_lugar_foto_alter_mujer_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mujer',
            name='campos_investigacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mujer',
            name='fechas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
