# Generated by Django 5.2.3 on 2025-07-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0004_migrate_areas_to_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mujer',
            name='areas_investigacion',
        ),
        migrations.AddField(
            model_name='mujer',
            name='areas_investigacion',
            field=models.ManyToManyField(blank=True, related_name='mujeres', to='mujeres.areainvestigacion', verbose_name='Áreas de investigación'),
        ),
    ]
