# Generated by Django 5.2.1 on 2025-05-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0004_mujer_campos_investigacion_mujer_fechas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mujer',
            name='campos_investigacion',
        ),
        migrations.AddField(
            model_name='mujer',
            name='areas_investigacion',
            field=models.ManyToManyField(blank=True, to='mujeres.areainvestigacion', verbose_name='Áreas de investigación'),
        ),
    ]
